package testJumble;


import static org.testng.AssertJUnit.assertEquals;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.testng.ITestResult;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;

public class Angles {

	static WebDriver driver1 ;
	static Wait<WebDriver> wait;
	static String URL_TO_TEST = "http://www.cs.nuim.ie/~pmooney/CS265B/2017/triangle.php";

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {

		System.setProperty("webdriver.chrome.driver", "C:\\Users\\alexm\\OneDrive\\Desktop\\Second Year\\Semester 1\\CS265-Software Testing\\Code from praticals\\chromedriver.exe");

		driver1 = new ChromeDriver();
		wait = new WebDriverWait(driver1,1);
		System.out.println("CS265 Selenium Lab: TESTING READY TO BEGIN");
	}

	@AfterClass
	public static void tearDownAfterClass() throws Exception {
		driver1.close();
		driver1.quit(); // close the drivers
		System.out.println("CS265 Selenium Lab: TESTING FINISHED");
	}


	@BeforeMethod
	public void setUp() throws Exception {
        driver1.get(URL_TO_TEST);
    	driver1.manage().window().maximize();
    	wait.until(ExpectedConditions.presenceOfElementLocated(By.id("theSubmitButton")));
	}

	public static void CS265BLab7_TestTemplate(String s1,String s2, String s3,
			String expectedAns)
	{
		System.out.println("START: The page title is now " + driver1.getTitle());

		driver1.findElement(By.id("angle1")).sendKeys(s1);

		driver1.findElement(By.id("angle2")).sendKeys(s2);

		driver1.findElement(By.id("angle3")).sendKeys(s3);

		driver1.findElement(By.id("theSubmitButton")).submit();

		System.out.println("PROCESS: The page title is now " + driver1.getTitle());

		String answerGenerated = driver1.findElement(By.id("triangle")).getText();

		System.out.println("The answer generated by the Triangle PHP processor is [" + answerGenerated + "]");

		String expectedAnswer = expectedAns;

		System.out.println("Our expected answer is [" + expectedAnswer + "]");

		try {
			Thread.sleep(40);
		} catch (InterruptedException e) {

			e.printStackTrace();
		}
		assertEquals(expectedAnswer,answerGenerated);

	}

	@Test(dataProvider="validData",description="Testing the application with VALID input data")
	public void validDataTests(String s1, String s2, String s3, String ans)
	{
		CS265BLab7_TestTemplate(s1,s2,s3,ans);
	}

	@Test(dataProvider="invalidData",description="Testing the application with INVALID input data")
	public void invalidDataTests(String s1, String s2, String s3, String ans)
	{
		CS265BLab7_TestTemplate(s1,s2,s3,ans);
	}

	@DataProvider(name="validData")
	public static Object[][] createValidData()
	{
		Object[][] validData =
		{
			{"60","60","60","EQUILATERAL"},
			{"60","70","50","SCALENE"},
			{"60","20","100","SCALENE"},
			{"70","10","100","SCALENE"},
			{"90","60","30","RIGHT ANGLE TRIANGLE"},
			{"30","60","90","RIGHT ANGLE TRIANGLE"}
		};
		return validData;

	}
	
	@DataProvider(name="invalidData")
	public static Object[][] createInValidData()
	{
		Object[][] invalidData =
		{
			{"60","0","60","ZERO ANGLES"},
			{"60","160","60","GREATER THAN 180"},
			{"-60","160","60","NEGATIVE ANGLES"},
			{"60","","60","INVALID TRIANGLE"},
		};
		return invalidData;
	}

    @AfterMethod
    public void takeScreenShotOnFailure(ITestResult testResult) throws IOException {
        if (testResult.getStatus() == ITestResult.FAILURE) {
            System.out.println(testResult.getStatus());
            String fn = new SimpleDateFormat("yyyy-MM-dd-HH-mm-ss").format(new Date()).toString();
            fn = "CS265_SeleniumLab_FailedTest_" + fn + ".png";
            File scrFile = ((TakesScreenshot) driver1).getScreenshotAs(OutputType.FILE);
            FileUtils.copyFile(scrFile, new File(fn));
        }
    }



}